import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const production = process.argv[2] === "production";

const banner = `/*
Orbit — Claude Chat/Code/Cowork inside Obsidian.
This file is generated by esbuild. Edit main.ts, not this file.
*/`;

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["main.ts"],
  bundle: true,
  // The Agent SDK IS bundled (esbuild converts its ESM to CJS), because a
  // runtime dynamic import cannot work inside Obsidian: the renderer's import()
  // is Chromium's, which refuses to fetch file:// modules. Bundling is what
  // Claudian does. Binary resolution is handled explicitly in main.ts via
  // pathToClaudeCodeExecutable, so the bundle never has to resolve it itself.
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  // The SDK calls createRequire(import.meta.url) at module load. In a CJS
  // bundle import.meta is undefined, which throws ERR_INVALID_ARG_VALUE before
  // any Orbit code runs. createRequire also accepts an absolute path, so map it
  // to __filename (Obsidian provides it, and Claudian's bundle does the same).
  define: { "import.meta.url": "__filename" },
  format: "cjs",
  platform: "node",
  target: "es2018",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production,
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
